version: '3'

volumes:
  postgres_data:
    driver: local

services:
  app:
    container_name: app
    build: .
    depends_on:
      - postgres
    ports:
      - '4000:4000'

  postgres:
    container_name: db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
